version: '3'
services:
  mariadb:
    image: 'mariadb:10.11.2'
    hostname: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083'
    volumes:
      - ./metastore_conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-network

  trino:
    image: trinodb/trino:410
    hostname: trino_container
    ports:
      - 8080:8080
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/catalog:/etc/trino/catalog
    networks:
      - trino-network
    depends_on:
      - minio
      - hive-metastore

  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: radit
      MINIO_SECRET_KEY: radit11047
    command: server /data --console-address ":9001"
    networks:
      - trino-network

  trino-setup:
    build: ./cli
    restart: "no"
    networks:
      - trino-network
    depends_on:
      - trino

  metabase:
    image: metabase/metabase:v0.45.3
    ports:
      - "3000:3000"
    networks:
      - trino-network
    volumes:
      - ./metabase/plugins:/plugins
      - ./metabase/data:/metabase-data
    environment:
      MB_PLUGINS_DIR: /plugins
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - trino

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - trino-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - trino-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - trino-network

volumes:
  trino:
    driver: local
  metastore_conf:
    driver: local
  minio-data:
    driver: local
  metabase:
    driver: local
  cli:
    driver: local
  grafana:
    driver: local

networks:
  trino-network:
    driver: bridge
